dist: trusty
sudo: required
git:
  depth: 3
language: ruby
cache: bundler
rvm:
- 2.4.1
addons:
  chrome: stable
env:
  secure: SfXwo6AwagHs58MSqsDILjcMEbtVpzmpXyCnfkZu1r0PJ2ZFxjF9YfyqYpRuJbCMS8OmHauLDYwbQwP0mh8U/EGhGq2ZLTGyjqUyniBWK5oFS2NqKADFhMtH/1G0rlSFDuL4ghHfTY+Wkfmr/Su7bvTyKXeTUzbP7kBxW2F1de9VlDO5WEpfjDPLu+IAI5dLTDypz1Gcvdo139nrBOLYwj+1djhYAhVdOXoaTchb/+8j/9i0r/EJsR0WvOGupVBQnyqCq73VTWkjJe+VbVdSV3CYWuvXWC8yp6ehQZDegPU+9Qy4LaWOQwEQkP0bUIUM4EPHCgqf3647E/0I2h4wjJbisgLO1VRZztfiXAtgjbchEBc4Dc2GzRCBLZijvFCPGK3TF5jpU8LXI8gVtZ5PoTFB67Gv9zSeWa+/Ww20P+8pZNttDInFkw1ZtkOw1F3HgDVgOOANI+5ebv9AvEgK85eo1W/WFrtuYpbtf3QWCWvG1F4qvjAjD+zepCQYwzId9cNVnH0kWVE9DVhzY5CX3e3n6okT2D2SGPTP05NSw6KJGTN7P6NDWDiSQ48f6odJDvLBMrM0MkB/o7gzfJ6gcz7Bb5iiH+AEubNQu8mzkiNBjmz9WnRsmGM/jS1o1ra+BLfX2W/Lnx4zOXO4pX31vRuwBgC/eTIxptPnN7ma06Y=
before_install:
- cd server
- bash scripts/travis-before-install.sh
before_script:
- mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
- mysql -e 'CREATE DATABASE uofmeme_app_test;'
script:
- whereis google-chrome-stable
- google-chrome-stable --version
- whereis chromedriver
- bundle install --path vendor/cache --quiet
- bash scripts/vagrant-tests.sh
install:
- wget -N http://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip
  -P ~/ --quiet
- unzip -q ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
after_success:
- bash scripts/deploy.sh
notifications:
  email: false
  slack:
    secure: T5Z6/s6fhPOjv671dWXfCSwl3p2dm7k2kKJKpNJiWymsojXLIg8bcOd0ocwnTyv59TPhIAmZkMxCHoEtuVKgcBnayMmQhSd/deomyXxL0N1RqiMUfa91S7PBeaRWe+5h8s0PmIWW4KSU/cw1MxWx/tsq3nVHvs2j5zWTUE1c7O4hSQD+y0FixNJn5QcUBG6GGIOEUVDYG7Z6wFEtQ0CKl66GCctFHl2YSq2fbERHK8RtEAFoYFoxAhd5o0FdO7E+6DlozKMJvo2C4fHgc+JlR2CIDPRPUHBu9EA1jjqe3ztt/m4DUjh/vf0r6h4gfp7m77xv83gxpCEPe1Icekla4xQvdrGgYuvpfoi+uahF556OmqLUzoxj4ae4YwtqpBhdd8V0PTI2f1FJjEeiElVCy1lsSRBlQrmRAyAEEU29Pcl/IadJmqdVtmJ9ovwfcB4T63t4N9o2OyW+QVOH/ATJG58o0fMTajHqzKSzQXYCtneGG34YQpeFR/JFpYnoFVZiIncMcSue8at2mtexMa5vpaAxGyEXVuMspLxvkeqzKlCt3hkHiv7pS1KxcUQF+GJE4CB0EAftomB2M04FAZHvWBcSzH95bo8Uuj9BP2xqynnfePIXqJ4ARgV7fZ7DB5y91ddsJ0oQGcgGEfIOJBiqSuS4PFg24j0VHxlsxKKKawY=
