# Load DSL and Setup Up Stages
require 'capistrano/setup'
require 'capistrano/deploy'

# Load Git SCM plugin
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git

require 'capistrano/rails'
require 'capistrano/bundler'
require 'capistrano/rvm'
require 'capistrano/puma'

require './lib/capistrano/remote_cache_with_project_root_strategy'

# Loads default puma tasks
install_plugin Capistrano::Puma
# Loads custom tasks from `lib/capistrano/tasks' if you have any defined.
Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }
